export { default as Aside } from './Aside'
export { default as Curriculum } from './Curriculum'
export { default as Footer } from './Footer'
export { default as Header } from './Header'
export { default as Skills } from './Skills'