export { default as About } from './About'
export { default as ContactForm } from './ContactForm'
export { default as Hero } from './Hero'
export { default as NavBar } from './NavBar'
export { default as Portfolio } from './Portfolio'
export { default as RRSS } from './RRSS'